### ISSUE TITLE
about memory bank.

### ISSUE THREAD

**Issue by mmyjjl1009** [hkchengrex/STCN#10]
sry, im not really understand why the memory bank can reduce the running time of  Memory/Value Encoder .
i think even though the feature of frame(t-1) has been saved,but you still need to encode the mask(t-1) and frame again,so where is the saved time reflected?
wating for your reply, thank you very much.

**Comment by hkchengrex** [comment]
Is Section 3.3 clear enough?

**Comment by mmyjjl1009** [comment]
> Is Section 3.3 clear enough?

just because not encode every frame(t-1) in eval round?

**Comment by hkchengrex** [comment]
That, together with computing affinity fewer times and a lighter value encoder.
If you write out the actual operations required, you can see how not encoding the temporary frame gives a huge boost. We counted the total in Section 3.3.

**Comment by mmyjjl1009** [comment]
yes i get it, thank you very much
