### ISSUE TITLE
Use multiple GPUs for evaluation 

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#100]
I want to use multiple GPUs for evaluation because it report `cuda out of memory` ,but it still only use one GPU when I replace 
`prop_model = STCN().cuda().eval()` 
`prop_model.load_state_dict(prop_saved)`
by
`prop_model = STCN()`
`prop_model = torch.nn.DataParallel(prop_model, device_ids=[0])`
`prop_model.load_state_dict(prop_saved, strict=False)`
`prop_model = prop_model.eval().cuda()`

Could you please give me some guidance on how to use multiple GPUs to evaluate the models?

**Comment by hkchengrex** [comment]
Data parallel is not going to work because the batch size is one. I don't think multiple GPUs can help... Why are you running out of memory? for which dataset?

**Comment by zhouweii234** [comment]
Because I modified the network. There is no problem with your original network.
I got it, thank you very much.

**Comment by hkchengrex** [comment]
`--amp` should help if you are not already using it.
