### ISSUE TITLE
How to test on davis 2017 testdev?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#101]
@hkchengrex How to test on davis 2017 testdev?  I don't think you gave me the code? You seem to have not given the relevant code?

**Comment by hkchengrex** [comment]
Same code, same model. It is mentioned in the readme. Set `mem_every` to 3 according to the paper.

**Comment by longmalongma** [comment]
> Same code, same model. It is mentioned in the readme. Set `mem_every` to 3 according to the paper.

Ok, thanks!
