### ISSUE TITLE
Are the results of your method in Table 3 both trained on DAVIS 2017 and YoutubeVOS 2018 together? 

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#102]
Have you only used the Youtube 2018 training set for training when evaluating Youtube 2018, or only used the DAVIS 2017 training set for training when evaluating DAVIS 2017?

**Comment by hkchengrex** [comment]
I used the same model (trained on YouTubeVOS 2019 and DAVIS 2017) for everything.
