### ISSUE TITLE
Run it completely on the CPU?

### ISSUE THREAD

**Issue by Rojinhassan** [hkchengrex/STCN#105]
Hi,
first, thanks for your great work!
Is it possible to run the trained model completely on the CPU and still get great results for real time videos foreground/background Segmentation in the range of 20 to 30 fps?
Thanks!

**Comment by hkchengrex** [comment]
You can look at ONNX: https://github.com/microsoft/onnxruntime but I don't suppose it is easy to achieve (with this model).

**Comment by Rojinhassan** [comment]
Okey, I will. thank you :)
