### ISSUE TITLE
How to install InterpolationMode?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#11]
How to install InterpolationMode?

![image](https://user-images.githubusercontent.com/40291722/124532379-fedc7280-de42-11eb-9e74-64e939b4cd3b.png)

**Comment by hkchengrex** [comment]
You probably need to update your `torchvision`. `InterpolationMode` exists for `torchvision>=0.9`.
https://pytorch.org/vision/0.9/transforms.html#torchvision.transforms.RandomAffine

**Comment by longmalongma** [comment]
> You probably need to update your `torchvision`. `InterpolationMode` exists for `torchvision>=0.9`.
> https://pytorch.org/vision/0.9/transforms.html#torchvision.transforms.RandomAffine

Ok, thanks for your reply.
