### ISSUE TITLE
Code Run Guidance

### ISSUE THREAD

**Issue by parthmalpathak** [hkchengrex/STCN#110]
Congratulations on your great work.
I need to implement a similar code for some research work and I have cloned this repo for reference. But I am having difficulties with where to start from while running the files. Any guidance to how I can generate similar results like yours on my system?

**Comment by hkchengrex** [comment]
Which part of "Reproducing the results" are you stuck at?

**Comment by parthmalpathak** [comment]
I need general guidance about which file runs when.

**Comment by hkchengrex** [comment]
The "Reproducing the results" section tells you which file to run.
