### ISSUE TITLE
Evaluation part which include the comparison of the standard metrics?

### ISSUE THREAD

**Issue by Rojinhassan** [hkchengrex/STCN#112]
Hi,

first thanks for your great work!
Is it possible to also upload your evaluation part which include the comparison of the standard metrics (region similarity J , contour accuracy F, and their average J&F) for DAVIS 2017?
That would be very helpful and thanks!

Best
Rojin

**Comment by hkchengrex** [comment]
Use the official routine: https://github.com/davisvideochallenge/davis2017-evaluation

**Comment by Rojinhassan** [comment]
Of Course, thank You!
