### ISSUE TITLE
BL30k examples

### ISSUE THREAD

**Issue by fingertap** [hkchengrex/STCN#115]
Can you show some examples of BL30k dataset? You report the results on YouTubeVOS 2018 is boosted by training on BL20K, yet the results on DAVIS is not. I'm curious about this, but the raw dataset is toooo large, so some examples from the dataset would be great!

**Comment by hkchengrex** [comment]
https://hkchengrex.github.io/MiVOS/dataset.html

**Comment by fingertap** [comment]
Cool!
