### ISSUE TITLE
关于batch size

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#117]
@hkchengrex 您好，我想请教一下在训练的时候预训练的batch size是多少？主训练的时候batch size是多少？论文中和现在的默认参数好像不一致？

![image](https://user-images.githubusercontent.com/40291722/159835662-8dd9454a-607d-4d3e-a13e-f37c53f8a7b4.png)

![image](https://user-images.githubusercontent.com/40291722/159835557-4188ae58-f9cc-48f3-9c69-f1056303eefd.png)

**Comment by hkchengrex** [comment]
See #45 
This batch size is per-process.

**Comment by longmalongma** [comment]
> See #45 This batch size is per-process.

@hkchengrex 哦哦，您的意思是每个gpu是batch4，然后训练用两个gpu，所以论文中写得batch为8？

**Comment by hkchengrex** [comment]
Yes.

**Comment by longmalongma** [comment]
> Yes.

Ok, thanks!
