### ISSUE TITLE
May I ask why this task can be called semi-supervised？

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#119]
Why this task can be called semi-supervised, since we did not train the network with unlabeled data？

**Comment by hkchengrex** [comment]
See DAVIS: https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Perazzi_A_Benchmark_Dataset_CVPR_2016_paper.pdf. "Supervision" is in a per-video sense.
