### ISSUE TITLE
Looking forward to your multi-scale testing code!

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#121]
Since AOT has published his code for multi-scale testing, in order to make a fair comparison between STCN-based methods and AOT-based methods on the youtube online benchmark, we look forward to your publication of the code for STCN-based multi-scale testing.

**Comment by hkchengrex** [comment]
Here you go.

https://github.com/hkchengrex/STCN/tree/ms/ms

**Comment by longmalongma** [comment]
> Here you go.
> 
> https://github.com/hkchengrex/STCN/tree/ms/ms

Thanks for your great work!
