### ISSUE TITLE
how to replace resnet 50 with swin transformer in backbone of STCN?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#123]
If I change the resnet 50 of STCN to SWIN Transformer in backbone, I notice that I need to change the decoder, other than that, is there anything else I need to change?

**Comment by longmalongma** [comment]
In other words, what other powerful backbone can we try to replace Resnet 50?  @hkchengrex

**Comment by hkchengrex** [comment]
I'm afraid that you would have to look at the code and do it yourself.
