### ISSUE TITLE
how to get the figure 6?

### ISSUE THREAD

**Issue by Liesy** [hkchengrex/STCN#124]
Hi,
Recently i'm trying to get the correspondences of the rest frames using the first frame of my own video, but the results are bad.
Could you open source the codes that can get the correspondences like figure6 in your paper?
Thanks in advance.

**Comment by hkchengrex** [comment]
You can use the code here to get started: https://github.com/hkchengrex/Mask-Propagation/blob/main/try_correspondence.py

**Comment by hkchengrex** [comment]
The logic is the same but you would have to change some code to fit it to STCN. I look at the attention map and manually put the symbols in Figure 6.

**Comment by Liesy** [comment]
thank you very much! I'll try it later.

**Comment by Liesy** [comment]
Does the MaskRGBEncoder and RGBEncoder have the same effect in [corr_network.py#L40](https://github.com/hkchengrex/Mask-Propagation/blob/ec9309f04ae3c98edb2eb5675c937a699d80006f/model/corr_network.py#L40) when getting the memory key in [try_correspondence.py#L60](https://github.com/hkchengrex/Mask-Propagation/blob/ec9309f04ae3c98edb2eb5675c937a699d80006f/try_correspondence.py#L60) ?

**Comment by hkchengrex** [comment]
Memory keys are not symmetric in MiVOS so the keys you get from the different encoders are different. This problem does not exist in STCN.

**Comment by Liesy** [comment]
thx
