### ISSUE TITLE
 I would like to ask a question about Youtube-vos2019 evaluation

### ISSUE THREAD

**Issue by BigBoomDream** [hkchengrex/STCN#125]
Hi, thanks for your excellent work.
I use the original STM work ( https://github.com/seoungwugoh/STM ), but I don't know how to evaluate Youtube-vos2019 evaluation. Can you tell me how the original STM evaluates Youtube-vos2019 evaluation.
Thanks again for your help

**Comment by hkchengrex** [comment]
It is the same as YouTubeVOS 2018. Use the command-line argument to pass the correct path to the YouTubeVOS version that you want to use.

**Comment by BigBoomDream** [comment]
> 它与 YouTubeVOS 2018 相同。使用命令行参数将正确的路径传递给您要使用的 YouTubeVOS 版本。

@hkchengrex  Thank you for your reply. 
On the original STM, I only learned about Davis17 evaluation, not Youtube-vos evaluation. I would like to know how to evaluate Youtube-vos without adopting your code.（Because I use the original STM and your STCN data processing may be different）
Thank you very much for your help, looking forward to your reply again

**Comment by hkchengrex** [comment]
You might find more help if you ask this question in the STM repo instead since you are asking about their code.
