### ISSUE TITLE
四gpu训练

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#133]
如果用4个gpu训练会不会快一点？4个gpu训练的话需要更改哪些训练代码？

CUDA_VISIBLE_DEVICES=0,1,2,3 OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 1236 --nproc_per_node=2 train.py --id 4gputrian --stage 2

@hkchengrex

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/STCN/issues/62
