### ISSUE TITLE
How to check DAVIS, YouTube performence??

### ISSUE THREAD

**Issue by JYKai** [hkchengrex/STCN#134]
![image](https://user-images.githubusercontent.com/116412969/217170587-ae6ef117-b532-46fb-93ec-2fa9d3deea4a.png)

I want to get a performance evaluation score like the following image. How do I do that? I ask because it is not listed in the evaluation code.

**Comment by hkchengrex** [comment]
We use official code to get the metrics.

For example, 
- DAVIS 2017 validation: [davis2017-evaluation](https://github.com/davisvideochallenge/davis2017-evaluation)
- YouTubeVOS 2018 validation: [CodaLab](https://codalab.lisn.upsaclay.fr/competitions/7685#participate)
- YouTubeVOS 2019 validation: [CodaLab](https://codalab.lisn.upsaclay.fr/competitions/6066#learn_the_details)
