### ISSUE TITLE
How to check dot product performance?

### ISSUE THREAD

**Issue by JYKai** [hkchengrex/STCN#135]
hello.

I am a master's student who was impressed by your dissertation.

Looking at your code, I want to check performance via dot product, not performance via L2 similarity.

As a result of implementing it myself, it doesn't match the suggested figure. But can I check the code for the dot product??

thank you

**Comment by hkchengrex** [comment]
Not sure what you mean exactly. You can change these two lines to convert them to a dot product.
https://github.com/hkchengrex/STCN/blob/c9c627e50a43c239736c298380fda1226c455724/inference_memory_bank.py#L34-L35
