### ISSUE TITLE
git.Repo() has an error

### ISSUE THREAD

**Issue by panzuwang** [hkchengrex/STCN#138]
在logger.py文件中，第46行
![image](https://user-images.githubusercontent.com/87985441/225640817-f58afa61-66a3-4aa9-bccf-af1c407795f0.png)
会有以下错误
![image](https://user-images.githubusercontent.com/87985441/225641522-7694f310-d39a-46bf-a50f-bfee141ca7dc.png)
当我把这两行注释掉后代码就能正常运行了。
不知道是什么原因，希望能够得到您的帮助，谢谢！

**Comment by hkchengrex** [comment]
You need to clone the repo (`git clone`). It is fine just to comment it out though.

**Comment by panzuwang** [comment]
> 

谢谢您的回复，我还有一个问题，如果我想在在一台3090gpu上运行您的多GPU训练文件train.py，除了改batch-size外不做其他修改通过以下命令运行：CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 python -m torch.distributed.launch --nproc_per_node=1 train.py --id retrain_s0 --stage 0 这是否有什么问题？期待您的回复，谢谢！

**Comment by hkchengrex** [comment]
It should be fine.

**Comment by panzuwang** [comment]
> 

我明白了，谢谢您的解答！
