### ISSUE TITLE
STCN 代码中的一些问题

### ISSUE THREAD

**Issue by karchen-geng** [hkchengrex/STCN#139]
prev_logits, prev_mask = self.STCN('segment', 
                        k16[:,:,1], kf16_thin[:,1], kf8[:,1], kf4[:,1], 
                        k16[:,:,0:1], ref_v, selector) 

您好，在分割三帧中的第二帧时，这段代码中的 kf16_thin[:,1]，是充当 query帧的value嘛，

**Comment by hkchengrex** [comment]
It is a skip-connection from the query encoder to the decoder.

**Comment by karchen-geng** [comment]
您好，network.py中的segment函数中，有一个注释 qv16 is f16_thin above，这个qv16是代表query帧的 value对吧

**Comment by hkchengrex** [comment]
You can look at it that way but fundamentally it is just a skip-connection.

**Comment by karchen-geng** [comment]
感谢！
