### ISSUE TITLE
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#14]
![image](https://user-images.githubusercontent.com/40291722/125034263-fc884b80-e0c2-11eb-9aed-6afe49bc71a7.png)
![image](https://user-images.githubusercontent.com/40291722/125034313-07db7700-e0c3-11eb-9e98-6103136c0793.png)
Is this because there is something wrong with my deep learning environment?What is the correct version of PyTorch, Python, and Cudatoolkit?

**Comment by hkchengrex** [comment]
See https://stackoverflow.com/questions/62359175/pytorch-says-that-cuda-is-not-available

**Comment by longmalongma** [comment]
> See https://stackoverflow.com/questions/62359175/pytorch-says-that-cuda-is-not-available

Ok, thank you very much, I got it!
