### ISSUE TITLE
只在视频数据集上训练的结果

### ISSUE THREAD

**Issue by karchen-geng** [hkchengrex/STCN#140]
您好，我想请问一下，您在文章中提到，只在main阶段训练精度为82.5，这个训练的iteration是多少呢？我的batchsize=4，训练400k iteration（因为我是单卡所以我把iteration翻倍，相应的step也翻倍了），在训练到300k时精度与您的一致，，但是我只训练300k iteration时无法达到您的精度。请问这正常嘛？

**Comment by hkchengrex** [comment]
I haven't tried training with one GPU with a batch size of 4. IIRC it was trained with 150K iterations (s3).

**Comment by karchen-geng** [comment]
thinks a lot
