### ISSUE TITLE
questions regard training the model

### ISSUE THREAD

**Issue by Liesy** [hkchengrex/STCN#141]
hi, 

recently I'm trying to train the model after replacing the backbone of encoder, but the resolution of input image is so large that the runtime error "CUDA out of memory" always occurs in training. 

I found that the forward step "MemoryReader.get_affinity()" in network.py tried to allocate 40GiB, so I wonder whether this function must compute the gradient? and how can I reduce the memory usage of GPU?

**Comment by hkchengrex** [comment]
You might convert that function to a for-loop that loops over the batch elements though I am not sure how much memory that can save. Reducing batch sizes/input resolutions are also useful.

**Comment by Liesy** [comment]
I'll try it later, thanks a lot.
