### ISSUE TITLE
How to put mask to image for YouTube datasets

### ISSUE THREAD

**Issue by csustYyh** [hkchengrex/STCN#148]
Hi!
Thanks for your great work. It's really helpful for my project research!
I'm trying to visualize seg. results，for DAVIS，it can work.
![image](https://github.com/hkchengrex/STCN/assets/118873316/56dbf283-7482-49cf-8b11-e285bdd2b6c0)
![image](https://github.com/hkchengrex/STCN/assets/118873316/9f939596-f651-4f85-9a99-20b58738d509)

However, for YouTube, the visualizing results look strange sometimes.
![image](https://github.com/hkchengrex/STCN/assets/118873316/4ea0cead-f1da-42e8-aad9-290bc2743830)
![image](https://github.com/hkchengrex/STCN/assets/118873316/265a523c-9b75-4666-a11c-a2f358800800)

Would you mind release your visualizing code for YouTube?
Thanks again，I greatly admire this work.（STCN）^ ^

**Comment by hkchengrex** [comment]
There are many resources for this:
https://stackoverflow.com/questions/10640114/overlay-two-same-sized-images-in-python
https://stackoverflow.com/questions/40895785/using-opencv-to-overlay-transparent-image-onto-another-image?rq=4

**Comment by csustYyh** [comment]
Thanks for your reply!
