### ISSUE TITLE
When training on single 4090, the GPU Util fluctuates a lot and the time estimated for training is very long.

### ISSUE THREAD

**Issue by isksjsksk** [hkchengrex/STCN#149]
I find that it costs share GPU memory. The bigger the num_worker sets, the more it costs. Is this the reason?
When setting num_worker=8
<img width="848" alt="微信截图_20230824204027" src="https://github.com/hkchengrex/STCN/assets/97522433/3f5276f8-1018-4211-acb6-66616864945d">
retrain_s0 - It    100 [TRAIN] [time         ]: 1.0258257

When setting num_worker=16
<img width="848" alt="16" src="https://github.com/hkchengrex/STCN/assets/97522433/3a866264-bbe0-4e07-930a-c96e0e67ebdf">
retrain_s0 - It    100 [TRAIN] [time         ]: 1.1624295

**Comment by hkchengrex** [comment]
I'm afraid that I cannot debug your training setup. The general advise is to check for CPU/GPU/IO bottlenecks.

**Comment by isksjsksk** [comment]
Thanks for your promt reply. In greater detail, my **CPU** is "i9-13900KF" 
 **GPU** is "NVIDIA GeForce RTX 4090" 
 **hard disk** is "Kingston KC3000 PCIe 4.0 NVMe M.2 SSD" 
 **memory** is "威刚 DDR5 6000MHz 32GB x 2" 
When I use iotop for monitoring IO Performance, I find that the Total DISK READ is always no more than 1000 K/s. So I think IO bottleneck is the problem and I am really confused about that.

**Comment by isksjsksk** [comment]
When I train on stage 3, the speed is quite fast and the time estimated is about 0.11. I wonder why such huge difference between stage 0 and 03. 
Is the reason my CPU is not powerful enough?
And do you have any advice to speed up training in stage 0 without losing performance?
Thanks for your excellent work!

**Comment by hkchengrex** [comment]
Sound like a CPU bottleneck but your CPU is not at full load. Perhaps try increasing the number of data loaders?

**Comment by isksjsksk** [comment]
It's quite strange that without making any modifications to the code or the experimental environment, the training process has significantly sped up now, with fluctuations ranging from 0.4+ to 0.6+.

**Comment by isksjsksk** [comment]
> It's quite strange that without making any modifications to the code or the experimental environment, the training process has significantly sped up now, with fluctuations ranging from 0.4+ to 0.6+.

I reconfigured the environment, and now the speed has improved. The S0 is around 0.3.
