### ISSUE TITLE
About top-k filtering 

### ISSUE THREAD

**Issue by csustYyh** [hkchengrex/STCN#150]
I am sorry to bother you.
When I used top-k, I found a problem that my input values might be large sometimes.
After 'values.exp_()', there will be 'INF'.
To avoid overflow, I change the computation as:
![image](https://github.com/hkchengrex/STCN/assets/118873316/50b53aa8-4123-4f09-83ec-98f8e8f3ced2)
Is it reasonable to make this change?

**Comment by hkchengrex** [comment]
Should be fine.
Ref: https://github.com/hkchengrex/XMem/blob/0151ab8b155d692549e77fbd9d307b61e4447072/model/memory_util.py#L41-L65
