### ISSUE TITLE
Why is normalization necessary in Equation 1?

### ISSUE THREAD

**Issue by xinbaiw** [hkchengrex/STCN#151]
Why is normalization necessary in Equation 1?

![image](https://github.com/hkchengrex/STCN/assets/143494439/16a5e009-abe9-47cf-84a3-403df7436416)

**Comment by hkchengrex** [comment]
Such that the readout is a weighted average of values. This is the same as STM.

**Comment by xinbaiw** [comment]
What effect does it have if the similarity score is not normalized and directly multiplied by the value of memory?

**Comment by hkchengrex** [comment]
It would not make sense to me.
