### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by 1334233852** [hkchengrex/STCN#152]
Thank you for your great work,but i have met a simple question...lol ,i use commands 'CUDA_VISIBLE_DEVICES=[0,1] OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 25763 --nproc_per_node=2 train.py --id first --stage 3 on the terminal.
torch.cuda.is_available() is  true,but there was an error
![微信图片_20231201173857](https://github.com/hkchengrex/STCN/assets/118711216/583b3763-76b1-4f9d-af69-c9cc615eeb0e)
I have done some debugging in various aspects, but it was not successful. How can I solve it? Thank you

**Comment by 1334233852** [comment]
sorry，Sorry, I made a basic mistake and changed it to             
`CUDA_ VISIBLE_ Devices=0,1 OMP_ NUM_ THREADS=4 Python - m torch. distributed. launch -- master_ Port 25762-- nproc_ Per_ Node=2 train. py -- id 111-- stage 3`
but still encountering a low-level problem
![1111](https://github.com/hkchengrex/STCN/assets/118711216/d3fbe78e-4980-40d2-a607-2988c97db049)
lol 
I added comments to this line of code
![22222](https://github.com/hkchengrex/STCN/assets/118711216/4ec43dbd-9535-47dc-998c-e290d2803ce8)
lol ,sorry,pls!  thank you， I searched online for a while but couldn't solve this problem ...  - -!

**Comment by hkchengrex** [comment]
And why did you comment out that line?

**Comment by 1334233852** [comment]
> And why did you comment out that line?
- - ！      I uncommented that line of code and adjusted the terminal command torch.distributed Launch -->torch. distributed. run modified the parameter single_object because my dataset is a single target. later,i met a problem :KeyError: sec_mask_1 ,single_object parameter was added to the LossCompute class. it is working properly.

**Comment by hkchengrex** [comment]
Thank you for letting me know that it is working properly.
