### ISSUE TITLE
Test with my own dataset

### ISSUE THREAD

**Issue by dongho-Han** [hkchengrex/STCN#157]
Hello!
I'm enjoying happy days with using your interesting works(STCN, XMem, DEVA, Cutie).
Also, I got much help from your previous answers. Thanks!
After all, I'm trying to run your models with my own dataset.
However, I got **two stucks**:
(1) I can easily make the RGB images, but **not the mask**. Could you share any ideas for that?
- Especially, all the models you made need first frame's mask, so making this mask is really important.
- Also, to evaluate, all the images' mask are needed.

(2)As I said, I'm trying to compare the outputs of STCN, XMem, DEVA, Cutie by running with my own dataset.
However, I think there is **no framework for testing the whole models by one-line code**. 
- Currently, I'm working on making each docker container for model and running on.
- Hopefully, I don't have to run all the models parallel(it could be run sequentially), but run in a one environment with simple code block would be great.
But, if you have any one-direct way to run all the models easily, I'll really happy to learn.

Thanks:)

**Comment by hkchengrex** [comment]
1. For manual annotation, you can use the interactive tool in Cutie. If you need the first-frame mask, copy it from the workspace. There are many other ways to annotate the mask depending on your application.
2. All the models support one-line command line evaluation if the dataset is set up properly. You can write a shell script to put them together.

**Comment by dongho-Han** [comment]
By using your tools, I think I can run your models with my custom dataset for only labeling first image, with the help of Cutie GUI.
Thanks!
