### ISSUE TITLE
Does the MemoryReader match between 3 frames or between all memory frames? 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#16]
Hi, your code reads 3 frames at a time for segmentation. Does the MemoryReader match between 3 frames or between all memory frames? After segmenting frame 2 with frame 0 and 1, how to segment frame3?

**Comment by hkchengrex** [comment]
Frame 0 -> given
Frame 1 -> from frame 0
Frame 2 -> from frame 1 and 2

There is no frame 3.

**Comment by longmalongma** [comment]
> Does the MemoryReader match between 3 frames or between all memory frames?

Thanks for your reply. Do you mean to take only 3 frames in each video sequence?  Does the MemoryReader match between 3 frames or between all memory frames?

**Comment by hkchengrex** [comment]
In training, only 3 frames are taken. Memory matching is between the frames that I mentioned above (left and right).

**Comment by longmalongma** [comment]
> In training, only 3 frames are taken. Memory matching is between the frames that I mentioned above (left and right).

Ok, I got it, thank you very much.
