### ISSUE TITLE
Why does running code on multiple GPUs not accelerate training?

### ISSUE THREAD

**Issue by qfxb** [hkchengrex/STCN#160]
We followed your suggested method for single GPU and dual GPU training and found that increasing the number of GPUs did not accelerate the training. Has the author encountered a similar issue? How can this be resolved?

**Comment by hkchengrex** [comment]
Duplicate: https://github.com/hkchengrex/STCN/issues/159

The batch size used in this codebase is a per-GPU batch size. By increasing the number of GPUs, you are also increasing the total batch size.

Please let me know if this does not answer your question.

**Comment by qfxb** [comment]
Thank you for your response. May I ask if the experiments in the paper were conducted on two GPUs? Could you provide information on the training time with dual GPUs (for example, using two 4090 GPUs)?

**Comment by hkchengrex** [comment]
> Models are trained with two 11GB 2080Ti GPUs ...
> ... pre-training takes about 36 hours and main training takes around 16 hours ...

from Section 5 of the paper.

**Comment by qfxb** [comment]
Training iterations are not set with a fixed "epoch" value but with a parameter like iterations. Can it be understood as: increasing the "batch_size" also increases the total training workload? Just like "Total training workload = batch_size * iterations"

**Comment by qfxb** [comment]
Training iterations are not set with a fixed "epoch" value but with a parameter like iterations. Can it be understood as: increasing the "batch_size" also increases the total training workload? Just like "Total training workload = batch_size * iterations"?
![91b8c152978f92ebc367a7637eecb2c](https://github.com/hkchengrex/STCN/assets/79034792/3dc67ed3-37f4-48b5-9abe-ea7385324bb8)

**Comment by qfxb** [comment]
> 训练迭代不是使用固定的“epoch”值设置的，而是使用迭代等参数设置的。能理解为：增加“batch_size”也增加了总的培训工作量吗？就像“总训练工作量 = batch_size * 迭代次数”一样？ ![91b8c152978f92ebc367a7637eecb2c](https://private-user-images.githubusercontent.com/79034792/346521855-3dc67ed3-37f4-48b5-9abe-ea7385324bb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzQxNjIsIm5iZiI6MTcyMDQzMzg2MiwicGF0aCI6Ii83OTAzNDc5Mi8zNDY1MjE4NTUtM2RjNjdlZDMtMzdmNC00OGI1LTlhYmUtZWE3Mzg1MzI0YmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEwMTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZDAzM2ZjNTE3ZDIwODNiNjIxOTc2M2YyNTk0OGVjMGZjN2ZiNThlNDQ2Mjk3MzY3MzdhYWEyMDBiNzFhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x2K3wN-BvxTVzZEf4f3aMEr6sk5clzSSdaoIBMsmJJ8)

Could you please add my email for communication? Here is my email:1069704910@qq.com

**Comment by hkchengrex** [comment]
Right. I believe these are nominal definitions in the field of machine learning. If you find email communication necessary, my email is listed in the readme file.
