### ISSUE TITLE
A quick question about the code and the training details

### ISSUE THREAD

**Issue by bellos1203** [hkchengrex/STCN#17]
Thanks for your great work and open-source code!
I have a quick question about the code related to the training details.

At line 161 in [train.py](https://github.com/hkchengrex/STCN/blob/main/train.py), there is a code to determine the maximum epochs to run.
https://github.com/hkchengrex/STCN/blob/5f11ad4491a7cb48d0f9d4951e02b4831e5951b5/train.py#L161

However, as far as I know, `len(train_loader)` equals to `dataset_size/batch_size`.
So the line becomes `para['iterations']/len(train_loader) == para['iterations']/(dataset_size/batch_size) == para['iterations']*batch_size/dataset_size`. 
The problem is, then the number of epochs to train **increases** as we increase the mini-batch size, which is not desirable behavior.

For instance, when I run the code for stage 0 with 2 gpus with `-b 8`, the total training epochs is 129.
However, when I run the code for stage 0 with 2 gpus with `-b 4`, the total training epochs is 65.
Moreover, when I run the code for stage 0 with 4 gpus with `-b 8`, the total training epochs is 258. 

It might not hurt the reproducibility of your amazing work, but I think it should be checked for scalability for the different batch sizes or different numbers of GPUs.

Or If I'm wrong, please let me know.

Thanks!

**Comment by bellos1203** [comment]
One more thing is that the total iteration increases after each mini-batch forward.  https://github.com/hkchengrex/STCN/blob/5f11ad4491a7cb48d0f9d4951e02b4831e5951b5/train.py#L188-L195

Then, is the exact total iteration for mini-batch size 16 is 30K * 16 = 480K, right?

**Comment by hkchengrex** [comment]
In our code and paper, we always fix the "number of iterations" and the number of epochs is only derived for reference. Some people, conversely, fix the number of epochs (which is consistent with your rationale). There are advantages to either one of them. In our defense, since we only pick three random frames from a video, "an epoch" in our code does not mean that we went through every single data point in the dataset -- it only means we used each video once, so "iterations" might be the better choice here.

And for your second question, an iteration always means a single forward pass regardless of batch size.

**Comment by bellos1203** [comment]
Thanks for your quick reply!
I understand your explanation about the term "iteration" and "epoch". 

However, my question still remains the same for both cases, since the question is actually about the **batch size**.
So, are you saying that the performance of your model is the same regardless of the batch size at least the total number of iterations of the forward pass are the same?
For instance, will the performance be the same for the case of 30K iteration with batch-size 64 and batch-size 1? (Of course, this is an extreme case :) )
I guess it would not, and I think the number of iteration needs to be adjusted if we change the batch size.

Do you have any results about the different numbers of the batch size?
Actually, I want to boost the training procedure with a larger batch size, and I think the training time could be reduced by using a smaller number of iterations.

Thanks!

**Comment by hkchengrex** [comment]
No, but the performance also would not be the same if we just keep the number of epochs the same. And I don't have an optimal conversion equation to change the number of iterations/epochs according to the batch size!

I haven't tried different batch sizes for computational reasons but you're welcomed to. I think the general advice is to increase LR and decrease the number of iterations.
