### ISSUE TITLE
RuntimeError: CUDA error: the launch timed out and was terminated

### ISSUE THREAD

**Issue by 1359347500cwc** [hkchengrex/STCN#21]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=702 : the launch timed out and was terminated
  0%|                                                                                                                  | 0/258 [06:58<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    model.do_pass(data, total_iter)
  File "/home/cwc/STCN_dd/STCN/model/model.py", line 160, in do_pass
    self.scaler.step(self.optimizer)
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 332, in step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 332, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
RuntimeError: CUDA error: the launch timed out and was terminated
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: the launch timed out and was terminated
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1614378083779/work/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f6e8e0592f2 in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f6e8e05667b in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7f6e8e2b2219 in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f6e8e0413a4 in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: std::vector<c10d::Reducer::Bucket, std::allocator<c10d::Reducer::Bucket> >::~vector() + 0x2f9 (0x7f6ee52d4169 in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: c10d::Reducer::~Reducer() + 0x26a (0x7f6ee52c912a in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: std::_Sp_counted_ptr<c10d::Reducer*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() + 0x12 (0x7f6ee52f03c2 in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #7: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 0x46 (0x7f6ee4c2c4a6 in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0xa1e6bf (0x7f6ee52f36bf in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x3665b0 (0x7f6ee4c3b5b0 in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x36781e (0x7f6ee4c3c81e in /home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x15893b (0x558167db293b in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #12: <unknown function> + 0x193141 (0x558167ded141 in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #13: <unknown function> + 0x15893b (0x558167db293b in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #14: <unknown function> + 0x193141 (0x558167ded141 in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #15: <unknown function> + 0x156d2c (0x558167db0d2c in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #16: <unknown function> + 0x159649 (0x558167db3649 in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #17: <unknown function> + 0x1670f2 (0x558167dc10f2 in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #18: _PyGC_CollectNoFail + 0x2a (0x558167e5464a in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #19: PyImport_Cleanup + 0x295 (0x558167e2fca5 in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #20: Py_FinalizeEx + 0x79 (0x558167e61a49 in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #21: Py_RunMain + 0x183 (0x558167e63893 in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #22: Py_BytesMain + 0x39 (0x558167e63ca9 in /home/cwc/anaconda3/envs/torch18/bin/python)
frame #23: __libc_start_main + 0xf0 (0x7f6f25c29840 in /lib/x86_64-linux-gnu/libc.so.6)
frame #24: <unknown function> + 0x1e21c7 (0x558167e3c1c7 in /home/cwc/anaconda3/envs/torch18/bin/python)

**Comment by hkchengrex** [comment]
Try: https://forums.developer.nvidia.com/t/xid-8-in-various-cuda-deep-learning-applications-for-nvidia-gtx-1080-ti/66433
