### ISSUE TITLE
The training time is too long

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#22]
I train stage 0 with 2×2080Ti  and it takes 4 days (about 96h). My parameters basically maintain your original settings, except that I set the `master_port` to `-29500` imitating other codes. The GPUs are at (almost) full load all the time.
![2](https://user-images.githubusercontent.com/62086490/126023672-dcbc1e1d-49d3-43a5-9956-172d0325b86a.png)

I also train to use higher OMP_NUM_THREADS (`OMP_NUM_THREADS= 8, num_workers = 8, batch_size=8`) or num_works  (`OMP_NUM_THREADS= 4, num_workers = 32, batch_size=8`). 
The `time` in log "retrain_s0 - It ******* [TRAIN] [time ]: ？" is `1.0+` when I use the modified settings above , and when I use your original settings (`OMP_NUM_THREADS= 4, num_workers = 8, batch_size=8`) the time is `0.8-0.9` around the start of training.
Therefore, even if I didn’t run the entire training process with other parameter settings, I judge that other parameter settings excpet your original settings will reduce the training speed.

The `time` in log "retrain_s0 - It ******* [TRAIN] [time ]: ？"  is 0.8-0.9 around the start of training，then it will drop to 0.6-0.7，however it rises to 1.5-1.6 after about 70 epoch. This is different from what you described in this answer https://github.com/hkchengrex/STCN/issues/5#issuecomment-869014828 . Could this be the reason why my training time is too long? Could you please give me some suggestions to shorten the training time?

**Comment by hkchengrex** [comment]
Four days is way too long...
If the GPUs are already almost always working, I don't really know why. You can try `--benchmark` if you haven't but that should not be significant.

**Comment by Limingxing00** [comment]
> I train stage 0 with 2×2080Ti and it takes 4 days (about 96h). My parameters basically maintain your original settings, except that I set the `master_port` to `-29500` imitating other codes. The GPUs are at (almost) full load all the time.
> ![2](https://user-images.githubusercontent.com/62086490/126023672-dcbc1e1d-49d3-43a5-9956-172d0325b86a.png)
> 
> I also train to use higher OMP_NUM_THREADS (`OMP_NUM_THREADS= 8, num_workers = 8, batch_size=8`) or num_works (`OMP_NUM_THREADS= 4, num_workers = 32, batch_size=8`).
> The `time` in log "retrain_s0 - It ******* [TRAIN] [time ]: ？" is `1.0+` when I use the modified settings above , and when I use your original settings (`OMP_NUM_THREADS= 4, num_workers = 8, batch_size=8`) the time is `0.8-0.9` around the start of training.
> Therefore, even if I didn’t run the entire training process with other parameter settings, I judge that other parameter settings excpet your original settings will reduce the training speed.
> 
> The `time` in log "retrain_s0 - It ******* [TRAIN] [time ]: ？" is 0.8-0.9 around the start of training，then it will drop to 0.6-0.7，however it rises to 1.5-1.6 after about 70 epoch. This is different from what you described in this answer [#5 (comment)](https://github.com/hkchengrex/STCN/issues/5#issuecomment-869014828) . Could this be the reason why my training time is too long? Could you please give me some suggestions to shorten the training time?

In my environment, I have to train the s0 stage for about 8 days, I think this is because of the IO device problem. So your training time is fast...

By the way, what are your results on different data sets?

**Comment by JerryX1110** [comment]
I've run more than 20+ exps and my observation is the training time really differs among machines.
