### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by RobinParmentier** [hkchengrex/STCN#23]
Hi,
Thank you for sharing this repository, it has been very helpful.
Unfortunately I keep getting RuntimeErrors when running the eval scripts:
"RuntimeError: CUDA out of memory. Tried to allocate 9.83 GiB (GPU 0; 4.00 GiB total capacity; 416.90 MiB already allocated; 2.34 GiB free; 446.00 MiB reserved in total by PyTorch)"
Traceback shows this is thrown by "rgb = data['rgb'].cuda()".
I suspect the GPU I am using does not have enough memory to store all frames from a video simultaneously. Could this indeed be the problem? And is there an easy way to fix this? Can frames be stored in smaller batches?
Thank you.

The GPU I am using : nvidia geforce gtx 1650.
This specific error was thrown while trying to evaluate my own data. It contains longer videos (ca. 1000 frames). But when running eval_davis.py I get a similar error.

**Comment by hkchengrex** [comment]
`eval_generic` does not store all the frames in the GPU simultaneously but still 4GB is not a lot and 1000 frames are too many. Increasing `mem_every` seems to be the easiest way.

**Comment by RobinParmentier** [comment]
Thank you for the response.
I tried using eval_generic, but I get "DefaultCPUAllocator: not enough memory" thrown by "images = torch.stack(images, 0)" in generic_test_dataset.py. I believe the images in this line contain all frames from a video and I was wondering if it would be possible to load the data in a different way so this problem could be circumvented.
Increasing mem_every doesn't seem to solve the problem as these errors occur before the inference core is initiated (the for data in progressbar line calls get_item on all videos and this is where the memory error occurs)

**Comment by hkchengrex** [comment]
Ah, I see. That's on CPU memory and not GPU memory. You can rewrite the loader and eval_generic to load one frame from disk to CPU at a time.
