### ISSUE TITLE
 How was 1620 obtained?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#24]
The mv dimension of the memory bank in the training code is: [4, 512, 2, 24, 24], and the mv dimension in the test code becomes: [1, 512, 1620]， How was 1620 obtained?

![image](https://user-images.githubusercontent.com/40291722/126032681-923c762a-5ebb-435e-ae15-4af267a29726.png)

**Comment by hkchengrex** [comment]
As stated in the code the third dimension is T*H*W

**Comment by longmalongma** [comment]
> As stated in the code the third dimension is T*H*W



> As stated in the code the third dimension is T*H*W

@hkchengrex What are the specific values of T, H and W?

**Comment by hkchengrex** [comment]
It depends on your code and data! Just do some more `print` in your code and it should be clear.
