### ISSUE TITLE
Dramatic performance degradation  w/o top-k trick

### ISSUE THREAD

**Issue by FrontierBreaker** [hkchengrex/STCN#25]
According to my retraining, I got ~84 J&F w/ top-k but ~80 J&F  w/o top-k. It seems this trick influences the overall performance greatly. Have you observed such a phenomenon in your exp?

**Comment by FrontierBreaker** [comment]
By the way, have you studied the selection of Hyper-param "K" in top-k filtering?

**Comment by hkchengrex** [comment]
Our s03 model drops to 84.1 without top-k. Top-k is a pretty neat trick and we have also applied it to the baseline in all ablation studies. We just tried a few values and picked 20.

**Comment by hkchengrex** [comment]
Please see the updated readme for further help in reproducibility.
