### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by GQLi-cong** [hkchengrex/STCN#26]
Thanks for your great work!

I retrained the code and used s03 model.I get 84.5 J&F on DAVIS17 val and 75.3 J&F on DAVIS17 testdev. 
Do you think the result are within a resonable range? I noticed that there are still some gaps compared to the result in your paper.
![no11](https://user-images.githubusercontent.com/75170869/126040410-ceed2746-3ccf-41d3-897c-5cc57edcacdf.jpg)
![no22](https://user-images.githubusercontent.com/75170869/126040413-5e599f49-3143-4e35-b17d-48a244365b0f.jpg)

**Comment by hkchengrex** [comment]
For testdev you would also need to set `mem_every` to `3`.
Try YouTubeVOS validation as well -- it seems to be more stable.

**Comment by hkchengrex** [comment]
84.5 for DAVIS is definitely lower than expected, but then again I do see unexplained variations sometimes in DAVIS especially in this high accuracy range probably due to its small size.

**Comment by GQLi-cong** [comment]
I get it. Thanks for your reply.
