### ISSUE TITLE
Request for details about STCN with wideresnet50+aspp backbone

### ISSUE THREAD

**Issue by JerryX1110** [hkchengrex/STCN#27]
Could you provide the performance, training schedule, and MS inference detail of  STCN with a wideresnet50+aspp backbone?

**Comment by hkchengrex** [comment]
Performance: 84.8 on YouTubeVOS19.
Training: Same as the baseline.
MS (from the paper): "For multi-scale testing, we feed the network with 480p/600p and original/flipped images and simply average the output probabilities.  As we trained our network with 480p images, we additionally employ kernelized memory reading [21] in 600p inference for a stronger regularization."

**Comment by JerryX1110** [comment]
Got that, thanks! What's the multi-scale ratio lists when you apply MS?

**Comment by JerryX1110** [comment]
Okay, I notice that in the appendix of the paper. Thanks for your immediate reply!

**Comment by longmalongma** [comment]
> Okay, I notice that in the appendix of the paper. Thanks for your immediate reply!

@JerryX1110 Have you implemented multi-scale testing by yourself?
