### ISSUE TITLE
How is the dimension of mk restored to (B, CK, T, H, W) or  (B, T, CK, H, W)   in _global_matching? 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#32]
How is the dimension of mk restored to (B, CK, T, H, W) in _global_matching? Because the dimension of mk in your training code is (B, CK, T, H, W).

![image](https://user-images.githubusercontent.com/40291722/127598289-cc7f8b1a-784b-4660-b7ff-74fd1656bd1b.png)

**Comment by hkchengrex** [comment]
`NE=THW`.
If you store T, H, and W, you can recover it.

**Comment by longmalongma** [comment]
> `NE=T*H*W`.
> If you store T, H, and W, you can recover it.

@hkchengrex In which line of code do you implement NE=T*H*W? I don't know what the values of T,H and W are.

**Comment by hkchengrex** [comment]
Here:
https://github.com/hkchengrex/STCN/blob/f08a2b4482f1a5186e410c584dc3a36b6a0cece6/inference_memory_bank.py#L70

And here:
https://github.com/hkchengrex/STCN/blob/f08a2b4482f1a5186e410c584dc3a36b6a0cece6/inference_memory_bank.py#L84

You can always just print out `H` and `W`. `T` is the number of times that concat happens.
