### ISSUE TITLE
Are you going to release the code for Multi-scale Testing and Ensemble?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#34]
![image](https://user-images.githubusercontent.com/40291722/127883520-062cf5b6-6a3c-41df-b4e8-4708134c1eee.png)

**Comment by hkchengrex** [comment]
No. They are purely engineering code.

**Comment by longmalongma** [comment]
> No. They are purely engineering code.
@hkchengrex Thanks for your reply. Does Wideresnet-50 need to load the pre-training model like resnet50?

**Comment by hkchengrex** [comment]
@longmalongma Yes.
