### ISSUE TITLE
Pretraining for the key and value encoder

### ISSUE THREAD

**Issue by LingyiHongfd** [hkchengrex/STCN#35]
Your work is excellent and interestind. And thanks for your code.
Now , I'm conducting some experiments on the modification and training on your model, but i met with some problem about pretraining. 
I has modified the model structure and retrain the model just follow your setting, and the result is not as expected.How can I ensure that the pretraining process is  adequate? Or How can I know whether more pretraining is needed?
And I don't know the difference between static image training and bl30k training except for multi-object. and the influence of the training on bl30k.
Many thanks, if you could notice this issue and answer my question.

**Comment by hkchengrex** [comment]
1. The default training schedule should be sufficient. I am currently investigating training performance fluctuations (some people can reproduce the performance while some cannot) and will post any updates on this repo.
2. Static image pretraining generates synthetic videos by planar augmentation while BL30K contains **real** motions including occlusions, disocclusions, etc.

**Comment by LingyiHongfd** [comment]
> 1. The default training schedule should be sufficient. I am currently investigating training performance fluctuations (some people can reproduce the performance while some cannot) and will post any updates on this repo.
> 2. Static image pretraining generates synthetic videos by planar augmentation while BL30K contains **real** motions including occlusions, disocclusions, etc.

Thanks for your rapid response.
