### ISSUE TITLE
 do I need to make changes to the test code as I change the training code?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#36]
Hello, I have made some changes to your training code based on your STCN baseline, but the test code is still the same. If I change the training code but do not change the test code, I can still test normally. Is that normal? Or do I need to make changes to the test code as I change the training code?

**Comment by hkchengrex** [comment]
That depends on the modification that you have made. Whether one thing is normal or not is based on your expectation.

**Comment by longmalongma** [comment]
> That depends on the modification that you have made. Whether one thing is normal or not is based on your expectation.

Ok, thanks.
