### ISSUE TITLE
How do I find the key and value of the first frame in your test code?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#37]
Where key_K and KEY_V are the memory frames saved with the first frame labeled, right? How do I find the key and value of the first frame in your test code?

![image](https://user-images.githubusercontent.com/40291722/128286790-7bd0e864-02f2-4405-b8de-c5d9f8e8e434.png)

**Comment by hkchengrex** [comment]
`key_k` and `key_v` are the key and value. What do you mean?

**Comment by longmalongma** [comment]
> `key_k` and `key_v` are the key and value. What do you mean?

@hkchengrex I mean here key_k and key_v are the key and value of the first frame with the label? I found that the key_k and key_v have no change in dimension with the increase of memory. In other words, how do I find the key and value of the labeled first frame in your test code? This question is very important to me, thank you.





![image](https://user-images.githubusercontent.com/40291722/128290920-91b74f5a-3922-4702-97cf-74760cba2626.png)

**Comment by hkchengrex** [comment]
Yes they are. Since they are "the first frame", of course their sizes don't change.

**Comment by longmalongma** [comment]
> Yes they are. Since they are "the first frame", of course their sizes don't change.

Ok, thank you very much!
