### ISSUE TITLE
Con't reimplement the performance reported in paper.

### ISSUE THREAD

**Issue by Alxead** [hkchengrex/STCN#39]
Hi, @hkchengrex 
I train a S03 model follow your command. And the final performance on DAVIS2017 is 0.839715 (not 85.4 reported in paper).
Does this performance is in the normal range ?

**Comment by hkchengrex** [comment]
Hi, I am currently investigating training performance fluctuations on different machines (some people can reproduce the performance while some cannot) and will post any updates on this repo.

**Comment by hkchengrex** [comment]
Please see the updated readme for further help in reproducibility.
