### ISSUE TITLE
Is it best to save 5 frames in memory frames? 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#40]
Is it best to save 5 frames in memory frames? I see that your code is saving 3 frames in memory.

![image](https://user-images.githubusercontent.com/40291722/128963051-f6d0fad2-68f0-4b28-a249-fbb948a1a255.png)

**Comment by hkchengrex** [comment]
You are probably confusing the memory for training and for testing. In training we use three frames in total, while in testing we take every fifth frame as memory.

**Comment by longmalongma** [comment]
> You are probably confusing the memory for training and for testing. In training we use three frames in total, while in testing we take every fifth frame as memory.

Ok, I got it, thanks!

**Comment by mathmax12** [comment]
@hkchengrex 
"in testing we take every fifth frame as memory"
Does that mean if there is a video having 100 frames and when process the last frame there will be around 95/5 = 19 frames in the memory?

**Comment by hkchengrex** [comment]
@mathmax12 20, to be more precise. The first frame is always saved.

**Comment by mathmax12** [comment]
Thanks.
