### ISSUE TITLE
Where is the code for no_cbam branch?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#41]
Where is the code for no_cbam branch? I did not find in your code

![image](https://user-images.githubusercontent.com/40291722/129201679-bd4b40aa-ba1c-457c-8e5f-e39ccb1a4772.png)

**Comment by JerryX1110** [comment]
Just in this repo. Switch to no_cbam branch instead of the main branch.

**Comment by longmalongma** [comment]
> Just in this repo. Switch to no_cbam branch instead of the main branch.

@JerryX1110 Can you check the link for no CBAM Branch? I didn't find it?

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/STCN/tree/no_cbam
