### ISSUE TITLE
Where can I find the key and value of the feature code of the labeled first frame in your test code?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#43]
I thought you said this was the key and value coding for the first frame with the label, but why do I encode the key for frame_idx and the value for self.images[:,frame_idx]?  

![image](https://user-images.githubusercontent.com/40291722/129700750-f686a48b-aec6-4f68-bdd0-d7879fae137e.png)

There is another problem. The dimension of the key here is: torch.Size([1, 512, 1, 30, 54]), and the dimension of the value is torch.Size([3, 512, 1, 30, 54]), The first dimension here is k (num_objects), what does the third dimension represent? Are the key and value here the feature encoding of the first frame with the label? Looking forward to your reply, thank you very much.
![image](https://user-images.githubusercontent.com/40291722/129701358-0d825cab-358d-47f6-8ecd-ce717ee1dc77.png)

**Comment by hkchengrex** [comment]
1. `frame_idx` is just `0`, representing the first frame most of the time. That interface is used to adapt to interactive/YouTubeVOS testing which is more complicated. From the propagation perspective, it is always the "first frame" in the propagation sequence.
2. The third dimension is time (`B*C*T*H*W` consistently in most places). It is just `1`, representing a single frame.

**Comment by longmalongma** [comment]
> 1. `frame_idx` is just `0`, representing the first frame most of the time. That interface is used to adapt to interactive/YouTubeVOS testing which is more complicated. From the propagation perspective, it is always the "first frame" in the propagation sequence.
> 2. The third dimension is time (`B*C*T*H*W` consistently in most places). It is just `1`, representing a single frame.
Thanks for your reply. In the YouTube dataset the first frame is labeled, right? How do I find labeled frames in test code?

**Comment by hkchengrex** [comment]
It is more complicated than that in YouTubeVOS. Check the dataset/our inference code for details.

**Comment by longmalongma** [comment]
> It is more complicated than that in YouTubeVOS. Check the dataset/our inference code for details.

@hkchengrex One thing I am confused about is how to store the value of frame 0 in memory if there is no GT on frame 0. Because value holds the features and the mask.

**Comment by hkchengrex** [comment]
@longmalongma Look at the youtube evaluation script for details. In short, we just skip the frames before the one with GT.

**Comment by longmalongma** [comment]
> @longmalongma Look at the youtube evaluation script for details. In short, we just skip the frames before the one with GT.


@hkchengrex I seem to understand. The key_k and key_v here may not be frame 0, but they must be frames with labels?

![image](https://user-images.githubusercontent.com/40291722/130198361-fa8d5db2-0da3-47bb-85cb-b1567f7aedbe.png)

**Comment by hkchengrex** [comment]
@longmalongma Yes.
