### ISSUE TITLE
Does the model with nproc_per_node=1 can only run on one GPU?

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#46]
The model is too big to run on one GPU, so I try to run the model with two GPUs and `nproc_per_node=1` (the training command is `CUDA_VISIBLE_DEVICES=2,3 OMP_NUM_THREADS=4 python -m torch.distributed.launch  --master_port -29500  --nproc_per_node=1 train.py --id retrain_s0 --stage 0`) . However, the code only use one GPU and still report `cuda out of memory`. I do not want to change `batch_size` and `num_works` because I'm afraid I'll get lower results. 

Does the model with nproc_per_node=1 can only run on one GPU? If so, could you kindly give me some suggestions to let the model run on two or more GPUs?

**Comment by hkchengrex** [comment]
If you set `nproc_per_node=1`, it will only use one GPU. If your GPUs have smaller memory, try reducing the batch size (like /2) and more GPUs (*2). Then each GPU handles a small batch and the total effective batch size would be the same. Cannot guarantee that the performance would be the same though (should be similar enough).

**Comment by zhouweii234** [comment]
@hkchengrex 
Thank you very much for your guidance.
What do you mean is that I should set the `nproc_per_node=4` and change the ` batch_size` in `hyper_para.py` to 1 / 2 of the original value, right? 
Do I need to change something else like `OMP_NUM_THREADS` or others?

**Comment by hkchengrex** [comment]
@zhouweii234 
1. Yes.
2. Probably not. `OMP_NUM_THREADS` affects training speed and the optimal setting really depends on individual machines. You might also want to change `num_workers` since it represents the number of data loader worker threads for each process. If you double the number of processes, the total number of workers would also be doubled.
