### ISSUE TITLE
Number of instances 

### ISSUE THREAD

**Issue by Trainingzy** [hkchengrex/STCN#48]
Thanks for your great work and code. 

I am new to this area, it seems that the maximum instance number is 2 for your code. How to deal with images with more than 2 instances?

**Comment by hkchengrex** [comment]
Memory is the only limit on the number of instances. We can definitely handle more than two instances.

**Comment by Trainingzy** [comment]
Thank you for your reply.

I am not sure but it seems that in your `vos_dataset.py` [here](https://github.com/hkchengrex/STCN/blob/e03c1585fd852624204b5c4e8d8e828ddb2d406f/dataset/vos_dataset.py#L180), you view all the instances except the first object as the second object. And in the forward process [here](https://github.com/hkchengrex/STCN/blob/e03c1585fd852624204b5c4e8d8e828ddb2d406f/model/model.py#L97), you also only use the two objects as in the dataset.

I mean that if the video has three instances, then the second object would include the second and third instances, right?

**Comment by hkchengrex** [comment]
`vos_dataset.py` is for training only and we indeed only handle two objects during training. That does not seem to affect our ability to generalize to more objects during test time.

**Comment by Trainingzy** [comment]
I got it. Thanks!

Btw, you only use two objects for training, because the training data only has two objects or just save the memory? do some training samples have more than two objects?

**Comment by hkchengrex** [comment]
Some have less than two (we always mask out the extra ones), and some have more than two. And yes we do it for training efficiency and memory consideration.

**Comment by Trainingzy** [comment]
I understand it now. Thank you~!
