### ISSUE TITLE
Questions about paper and code

### ISSUE THREAD

**Issue by Trainingzy** [hkchengrex/STCN#50]
Hi, thank you for your great work! I have several questions about the paper and code.

1. For the L2 distance, you discard one term [here](https://github.com/hkchengrex/STCN/blob/e03c1585fd852624204b5c4e8d8e828ddb2d406f/inference_memory_bank.py#L34), why you do that?
2. I don't know how you only calculate the affinity matrix once for a frame with multiple instances? I think memory is instance-specific and for each instance, we have one memory, so the affinity should be calculated for each instance. I think it is the same with [your test code](https://github.com/hkchengrex/STCN/blob/e03c1585fd852624204b5c4e8d8e828ddb2d406f/inference_core_yv.py#L83).
3. I am new to this area, how can I get the quantity results? I seems that you only save the images.

Look forward to your reply.

**Comment by Trainingzy** [comment]
Thank you for your reply and your contribution to the community~~

**Comment by hkchengrex** [comment]
The paper (appendix section A) has been updated to reflect point (1).
