### ISSUE TITLE
About the results written in the paper 

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#51]
Why the result of CFBI+ do not use the best results in the paper (CFBI+2× and CFBI+MS, i.e. the two lines framed by the red frame in the second figure)?
![4423092850d2f3d85cbb839181788b4](https://user-images.githubusercontent.com/62086490/131217134-468ca320-2054-4957-977b-10c4996870fb.png)
![59fb0b0b78941b8a722433a704f2c90](https://user-images.githubusercontent.com/62086490/131217152-799ca7a1-37e1-407f-b1ba-5cc913d5555b.png)

**Comment by hkchengrex** [comment]
1. Multi-scale/flip (MS) testing is a technique that is known to improve the performance of almost all segmentation methods, and is commonly *not employed* in the standard setting. Most (perhaps all) other methods in the table also do not employ multi-scale testing. It is only fair to not compare with CFBI-MS.
2. We also consider the 2X scheduling to be non-standard for several reasons. 1) it is not used in the original CFBI paper; 2) it is not used in the DAVIS setting; 3) the training resources required for the 1X setting is already huge (4X V100), doubling the batch size would mean **8X V100**. The resources used in the 1X setting is closer to the usual practice.
