### ISSUE TITLE
The memory size every GPU use is different

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#52]
![屏幕截图 2021-08-29 113902](https://user-images.githubusercontent.com/62086490/131237530-bd7ed358-5618-4df1-9758-88dd27f29262.png)
I found that the memory every GPU use is different, it is strange because I have run your code several times before and the memory size every GPU use is the same. I am sure that I use `python -m torch.distributed.launch` and `nproc_per_node=4` to train the code. Is this normal? Or did i do something wrong?
If this is not normal, do you know the problem is generally caused by what kind of error?

**Comment by hkchengrex** [comment]
That might happen if you use `--benchmark`. When that happens, training tends to be slower due to imbalance (probably different algorithms are picked for different GPUs) in my experience. I am not sure *why* it happens.
BTW your GPU0 seems much more overworked...

**Comment by zhouweii234** [comment]
Thank you very much for your guidance! But I do not use `--benchmark`, so do you know other possible causes of this problem?

**Comment by hkchengrex** [comment]
Are there other processes running on the GPUs?
