### ISSUE TITLE
Do you use top-k trick in the code?

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#53]
You mentioned in this answer that you applied top-k trick to the baseline in all ablation studies. (https://github.com/hkchengrex/STCN/issues/25#issuecomment-881896022)
But top-k trick doesn't seem to be applied in your code in `get_affinity()`  (in `network.py`). Is it because I misunderstood your code or the code you provided does not use top-k trick？

**Comment by hkchengrex** [comment]
It's in evaluation only: https://github.com/hkchengrex/STCN/blob/e03c1585fd852624204b5c4e8d8e828ddb2d406f/inference_memory_bank.py#L37
