### ISSUE TITLE
If I test on YouTube test, what else do I need to change besides --split test?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#56]
If I test on YouTube test, what else do I need to change besides --split test? Do I need to change valid to test here?
![image](https://user-images.githubusercontent.com/40291722/132855549-3b25ced2-c6ff-489c-a407-b68f8e38a902.png)

**Comment by hkchengrex** [comment]
Just make sure you have the two folders: YouTube/test and YouTube/all_frames/test. You don't have to change that.
