### ISSUE TITLE
Performance on the DAVIS datasets

### ISSUE THREAD

**Issue by suhwan-cho** [hkchengrex/STCN#6]
Hi, thanks for your great work!!

Could you provide the performance on the DAVIS datasets without using YouTube-VOS for network training?
Specifically, performance if using 1. DAVIS  2. Static+DAVIS  3. Static+BL30K+DAVIS.

**Comment by hkchengrex** [comment]
I believe in data-driven methods. The most important (IMO) reason that some people train on DAVIS only is to compare with previous methods that are created when YouTubeVOS did not exist. That has changed and we can now compare with several methods that do use YouTubeVOS. 

If less labeled data is desired, I think mass unlabeled data + small labeled data is the way to go. Simply reducing labeled data does not seem to be a good use of our training resources/energy.

If you really need those results you can always modify our open-sourced code to train these models. I can provide support if you encounter any problems in doing so.

**Comment by JerryX1110** [comment]
I think this model simply needs more data to learn the correspondence between image pairs better.

**Comment by hkchengrex** [comment]
Pure guess, haven't tried anything: we need less data than STM (shared key encoders impose prior) but more data than CFBI (which is more structured).

Feel free to reopen if you want to discuss/add your experimental results here.
