### ISSUE TITLE
How do we find the mask of the previous frame before segmentation?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#60]
Why do you do encode_value first and then encode_value? How do we find the mask of the previous frame before segmentation?

![image](https://user-images.githubusercontent.com/40291722/133920636-b32c44f8-edcd-4fb1-b83d-617b4e84e25f.png)

**Comment by hkchengrex** [comment]
I don't quite understand your question (from the screenshot it is apparent that we segment first?). We segment first, then encode the segmented frame as memory if required.

**Comment by longmalongma** [comment]
> I don't quite understand your question (from the screenshot it is apparent that we segment first?). We segment first, then encode the segmented frame as memory if required.
@hkchengrex 
In line 83, what if I want to introduce the predictive mask of the previous frame while segmenting the current frame?

**Comment by longmalongma** [comment]
> > I don't quite understand your question (from the screenshot it is apparent that we segment first?). We segment first, then encode the segmented frame as memory if required.
> > @hkchengrex
> > In line 83, what if I want to introduce the predictive mask of the previous frame while segmenting the current frame?

@hkchengrex Can the code be used to take the predicted mask of the video frame? self.prob[self.enabled_obj,frame_idx] 

If I take the second predicted target on frame 3 is that right?
 self.prob[2,3]

**Comment by hkchengrex** [comment]
Yes. And you can use that to extract the previous frame.

**Comment by longmalongma** [comment]
> `self.prob[object_idx, frame_idx]` represents the soft mask of the `object_idx`-th object at the `frame_idx`-th frame.
> `0` is the object index for the background, so `1` is the object index for the first object.
@hkchengrex Sorry, I'm confused 0 is the index for the background, why not 0 is the object index for the first object,`1` is the object index for the second object?

![image](https://user-images.githubusercontent.com/40291722/134269884-950ce6da-dc5d-4a70-a80b-52fde9014d78.png)

**Comment by hkchengrex** [comment]
After `aggregate(out_mask, keep_bg=True)`, background probability will be generated.

**Comment by longmalongma** [comment]
> After `aggregate(out_mask, keep_bg=True)`, background probability will be generated.
 @hkchengrex Ok, thanks for your reply.  If the current frame is TI, what is the index of the labeled first frame?

**Comment by hkchengrex** [comment]
0

**Comment by longmalongma** [comment]
> 0

Ok, I got it!

**Comment by longmalongma** [comment]
> 0

@hkchengrex  If the current frame is ti, the index of the previous frame is ti-1. Do I need to consider interval frames?

**Comment by hkchengrex** [comment]
What do you mean by "need to"?

**Comment by longmalongma** [comment]
> What do you mean by "need to"?

@hkchengrex Is there an interval between the current frame and the previous frame? If there are d intervals, the previous frame of the current frame ti is ti - d, not ti -1, right?

**Comment by hkchengrex** [comment]
The previous frame is at `ti-1`. There is no interval between frames. If you are talking about the previous *memory frame*, that's a different concept and you should be able to compute that as well.

**Comment by longmalongma** [comment]
> > 0
> 
> @hkchengrex If the current frame is ti, the index of the previous frame is ti-1. Do I need to consider interval frames?
> 
> > What do you mean by "need to"?
> 
> @hkchengrex Is there an interval between the current frame and the previous frame? If there are d intervals, the previous frame of the current frame ti is ti - d, not ti -1, right?



> that's a different concept and you should be able to compute that as well.

Ok, I got it, thank you very much!
