### ISSUE TITLE
Why the s0 model cannot be used directly for evaluation?

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#61]
I know that s0 model cannot to be loaded in the evaluation network, but I fail to find the difference between s0 and s03 models after reading the code. Could you kindly give me some guidance about it?

**Comment by hkchengrex** [comment]
It's actually very minor: s0 model handles a single model and s03 model handles multiple objects. So the s03 model accepts an extra channel input that is the sum of all other masks (this follows STM).

s0 model:
https://github.com/hkchengrex/STCN/blob/e03c1585fd852624204b5c4e8d8e828ddb2d406f/model/modules.py#L61

s03 model: 
https://github.com/hkchengrex/STCN/blob/e03c1585fd852624204b5c4e8d8e828ddb2d406f/model/modules.py#L96

And the conversion code is here (we randomly init the extra channel):
https://github.com/hkchengrex/STCN/blob/e03c1585fd852624204b5c4e8d8e828ddb2d406f/model/model.py#L219-L224

You can use the s0 model for evaluation with some code changes -- the easiest way is to implement the same conversion, but zero-init the extra channel.
