### ISSUE TITLE
How to take the prediction mask of each target in the previous frame? 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#64]
@hkchengrex Because two targets are fixed during training, prev_mask[:,0:1] and prev_mask[:,1:2] can be used to take the masks of the two targets in the previous frame. However, the number of targets during testing is not fixed. How to take the prediction mask of each target in the previous frame? 

for i, oi in enumerate(self.enabled_obj):
    self.prob[self.enabled_obj,ti-1].cuda()

![image](https://user-images.githubusercontent.com/40291722/134946737-304290a3-4361-4a11-a6d7-2f20cc73a00e.png)

![image](https://user-images.githubusercontent.com/40291722/134946862-2a4f4af4-34b6-46c8-befc-c6bbc69d3da6.png)

**Comment by hkchengrex** [comment]
You're right.
`self.enabled_obj` is a list containing object indices that we have seen.

**Comment by hkchengrex** [comment]
No. I don't understand what exactly you mean but you can always use indexing to extract whatever you need.
Here is a tutorial: https://numpy.org/doc/stable/reference/arrays.indexing.html

**Comment by longmalongma** [comment]
> No. I don't understand what exactly you mean but you can always use indexing to extract whatever you need.
> Here is a tutorial: https://numpy.org/doc/stable/reference/arrays.indexing.html

@hkchengrex         Is that how I take the predictive mask of all the targets?
for i, oi in enumerate(self.enabled_obj):
                                     self.prob[self.enabled_obj,ti-1].cuda()
Does self.prob[0,ti-1].cuda() represent background for previous frame?
Does self.prob[1,ti-1].cuda() represent  the predictive mask of the first target for previous frame?
Does self.prob[2,ti-1].cuda() represent  the predictive mask of the second target for previous frame?

**Comment by hkchengrex** [comment]
Yes.
That seems to be already explained in another issue that you opened: https://github.com/hkchengrex/STCN/issues/60

**Comment by longmalongma** [comment]
> Yes.
> That seems to be already explained in another issue that you opened: #60

Ok, thank you very much!

**Comment by longmalongma** [comment]
> > Yes.
> > That seems to be already explained in another issue that you opened: #60
> 
> Ok, thank you very much!

@hkchengrex            
 for i, oi in enumerate(self.enabled_obj):
                 self.prob[oi, ti-1].cuda().unsqueeze(0))
                print(self.prob[oi, ti-1].cuda().size())

                 torch.Size([1, 480, 864])
                print(self.prob[self.enabled_obj, ti-1].cuda().size())
                 torch.Size([3,1, 480, 864])
So I want to code mask, I have to, right?
                 self.prob[oi, ti-1].cuda().unsqueeze(0))
or   self.prob[oi, ti-1].cuda().unsqueeze(1))

**Comment by longmalongma** [comment]
> > Yes.
> > That seems to be already explained in another issue that you opened: #60
> 
> Ok, thank you very much!

@hkchengrex            
 for i, oi in enumerate(self.enabled_obj):
                 self.prob[oi, ti-1].cuda().unsqueeze(0))
                print(self.prob[oi, ti-1].cuda().size())

                 torch.Size([1, 480, 864])
                print(self.prob[self.enabled_obj, ti-1].cuda().size())
                 torch.Size([3,1, 480, 864])
So I want to code mask, I have to, right?
                 self.prob[oi, ti-1].cuda().unsqueeze(0))
or   self.prob[oi, ti-1].cuda().unsqueeze(1))

**Comment by hkchengrex** [comment]
Whether to use unsqueeze depends on your needs.
