### ISSUE TITLE
Can the value of different targets be encoded by simply switching the mask positions of different targets?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#66]
Hi, 
1. When feature concat is used, the value of different targets can be encoded only by exchanging the mask of different targets?However, I don't think the exchange of mask positions of different targets in concat has any effect on the result. 2. Can the ref_v1 and ref_v2 output here be called target features?

![image](https://user-images.githubusercontent.com/40291722/135402640-bc4fa019-f0b4-4e3e-9e7a-5de7516ada20.png)

**Comment by hkchengrex** [comment]
1. I didn't write the code that you highlighted.
2. If we don't know the target mask how can we decode the object?

**Comment by longmalongma** [comment]
> 1. I didn't write the code that you highlighted.
> 2. If we don't know the target mask how can we decode the object?



> 1. I didn't write the code that you highlighted.
> 2. If we don't know the target mask how can we decode the object?

@hkchengrex Sorry, I have updated the picture, I just don't understand how to know the value of each target when encoding the value of memory frame.Because only the positions of the predicted masks of different targets change during value coding.

**Comment by hkchengrex** [comment]
The "positions" control the function arguments. The first mask is the main object mask and the second mask is the mask for other objects (this follows from STM).
