### ISSUE TITLE
Hyperparameters for training without BL30k

### ISSUE THREAD

**Issue by Ali2500** [hkchengrex/STCN#68]
Hi,

I want to know if the hyperparameters (or any other settings) need to be changed in order to achieve the result given in Table 3 of the paper without BL30k (i.e. 85.4 on DAVIS and 83.0 on Youtube-VOS). Would I get similar results if I simply skipped the BL30k training stage (i.e. stage 1) from the existing code?

**Comment by hkchengrex** [comment]
The current code already supports training without BL30K. Take a look at "train a s03 model" near the end of the readme.

Also from the readme: "s012 denotes models with BL pretraining while s03 denotes those without (used to be called s02 in MiVOS)."
