### ISSUE TITLE
Are you sure it's better to get rid of CBAM?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#69]
Are you sure it's better to get rid of CBAM? But I did the experiment, and it got worse without cbAM.

**Comment by hkchengrex** [comment]
I am not saying that it's better to not have it. I am saying that it is not crucial.

**Comment by longmalongma** [comment]
> I am not saying that it's better to not have it. I am saying that it is not crucial.

Ok, thanks!
