### ISSUE TITLE
Why does Youtube’s max_skip need to be divided by five but Davis doesn’t? 

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#75]
Because Youtube is shorter than davis?

**Comment by hkchengrex** [comment]
YouTubeVOS only provide annotations for every 5th frame. The effective skip is the same.

**Comment by zhouweii234** [comment]
If I want to get previous gt mask of the 3 frame in training dataloader of YouTubeVOS and Davis, can I simply use `frames[f_idx-1][:-4] + '.png'` (line `129` in `vos_dataset.py`) to get the name of the 3 previous gt mask?

**Comment by hkchengrex** [comment]
For YouTubeVOS that would be **5 frames** before the selected frame as mentioned above. You need to beware of out-of-bound cases, but otherwise it will work fine.
