### ISSUE TITLE
Are there any other training techniques that might be useful for replicating your results?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#76]
Hi, @hkchengrex ,I have trained and tested several times according to your instructions, but I still cannot reproduce the accuracy in your paper. Are there any other training techniques that might be useful for replicating your results? By the way, will adding -no_amp during training improve the accuracy even further?

**Comment by hkchengrex** [comment]
Are you using the latest code unmodified and the exact software versions (most of them should not matter -- just to be safe)? There are no additional tricks. I just trained it using the shown commands and as mentioned I got DAVIS J&F in [85.1, 85.5] across multiple runs.

Someone else has also reported that they can reproduce the performance here: https://github.com/hkchengrex/STCN/issues/7

You can try without amp.
