### ISSUE TITLE
The performance gains from image datasets

### ISSUE THREAD

**Issue by bo-miao** [hkchengrex/STCN#82]
Hi,

Thanks for the great work.

Have you tried to train the model only on DAVIS and YOUTUBE (s3 only)? In that case, may I know the performance gap that training with/without static image datasets?
In addition, may I know your CPU information since my i9 7900x is very slow on static images?

Many thanks in advance.

**Comment by hkchengrex** [comment]
"s3 only", aka "main only" is shown in Table 7. Static image pertaining is crucial as in STM and related networks.
I don't know the exact CPU model (I no longer have access to that server), but it should be a server-grade one that is probably quite fast.
If pretraining is too slow for you, you can try to reduce the number of iterations. It probably converged before all 300K iterations but I cannot say for sure.
You can also try to reduce the frequency of calling TPS which is slow:
https://github.com/hkchengrex/STCN/blob/4d8b66fad07ef811f23b012c0af6f765ea767245/dataset/static_dataset.py#L115
(reduce 0.33 to a smaller number)

**Comment by bo-miao** [comment]
Great. Thank you for your detailed answer.
