### ISSUE TITLE
The next frame after ti is ti+1, right?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#95]
Ti is the current frame. After ti is segmented and saved as a memory frame, the next frame to be segmented is Ti +1.

Same question. Frame_idx is saved and the next frame to split is frame_idx +1.

![image](https://user-images.githubusercontent.com/40291722/139528245-64f5c0a5-89a9-450c-8610-53ecce208dfa.png)

![image](https://user-images.githubusercontent.com/40291722/139528240-932adbf2-b6f1-47a0-a0b6-2c453eda14c3.png)

**Comment by hkchengrex** [comment]
"The next frame after ti is ti+1" -- of course
What exactly is your question?

**Comment by longmalongma** [comment]
> What exactly is your question?









> "The next frame after ti is ti+1" -- of course What exactly is your question?



> "The next frame after ti is ti+1" -- of course What exactly is your question?

@hkchengrex How to extract the nearest frames while encoding the current frame?

**Comment by hkchengrex** [comment]
If the current frame is `ti`, then the nearest frames are `ti-1` and `ti+1`, subject to boundary conditions.

**Comment by longmalongma** [comment]
> If the current frame is `ti`, then the nearest frames are `ti-1` and `ti+1`, subject to boundary conditions.

Ok, thaks, I got it!
