### ISSUE TITLE
How do I save loss and IOU files to log during network training?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#96]
How do I save loss and IOU files to log during network training?

![image](https://user-images.githubusercontent.com/40291722/139639689-ae68b779-6caf-4dc7-96a7-818343df856e.png)

![image](https://user-images.githubusercontent.com/40291722/139639712-f686d1b3-358d-4e86-b23e-8c38af9e183c.png)

**Comment by hkchengrex** [comment]
Did you clone this project as a repository? This part only works in in git repo.

**Comment by longmalongma** [comment]
> Did you clone this project as a repository?

@hkchengrex No, I need to clone the project and put it where?How to operate?I didn't save the training log during my previous training.

**Comment by hkchengrex** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

Or you can just comment those two lines out.

**Comment by longmalongma** [comment]
> https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
> 
> Or you can just comment those two lines out.

I have tried just commented those two lines out.  But doing so does not save the training log.

**Comment by hkchengrex** [comment]
That should not be the cause. What is your training command?

**Comment by longmalongma** [comment]
> That should not be the cause. What is your training command?

@hkchengrex I used your default training command, but this command only saves the model, not the training log.
CUDA_VISIBLE_DEVICES=0,1 OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 2675 --nproc_per_node=2 trainon.py --id STCN --stage 2  --benchmark

**Comment by hkchengrex** [comment]
The command seems fine. Note that you are using `trainon.py` so I don't know what changes you have made.

**Comment by longmalongma** [comment]
> The command seems fine. Note that you are using `trainon.py` so I don't know what changes you have made.

@hkchengrex No, I didn't make any changes to your this code, nor can I save the training log when I replay your code.

**Comment by hkchengrex** [comment]
Are there any related error/warning messages? I can generate the log files in `/log` using the same command.

**Comment by longmalongma** [comment]
> 是否有任何相关的错误/警告消息？我可以`/log`使用相同的命令生成日志文件。



> Are there any related error/warning messages? I can generate the log files in `/log` using the same command.
No, and I didn't make any changes. Except invalidate those two lines of code

**Comment by longmalongma** [comment]
> Are there any related error/warning messages? I can generate the log files in `/log` using the same command.

我的也可以生成log文件，但log文件里面只有训练好的模型，无法将训练loss和训练iou保存到text文件中。

**Comment by hkchengrex** [comment]
Model files are saved in saves/, and log files are saved in log/ as a tensorboard log file. There is no text document.

**Comment by longmalongma** [comment]
> Model files are saved in saves/, and log files are saved in log/ as a tensorboard log file. There is no text document.

@hkchengrex Ok, How do i  ues a tensorboard log file? such as 

events.out.tfevents.1634553997.m162.62791.0

**Comment by hkchengrex** [comment]
https://www.guru99.com/tensorboard-tutorial.html

**Comment by longmalongma** [comment]
> https://www.guru99.com/tensorboard-tutorial.html

Ok, thank you very much!
