### ISSUE TITLE
How do I encode the value of the memory frame?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#97]
If I want to encode three objects, how do I encode the value of the memory frame?

![image](https://user-images.githubusercontent.com/40291722/140334040-f6ff41fe-a000-4a67-b50b-c075e2d3abad.png)

**Comment by hkchengrex** [comment]
The last argument is the sum of all other masks. 
The rest should be straightforward.

**Comment by longmalongma** [comment]
> The last argument is the sum of all other masks. The rest should be straightforward.

@hkchengrex Is there a difference in the order of the 3 masks?There are 6 combinations of 3 masks,
How many encode_values does it take to encode three targets?

**Comment by hkchengrex** [comment]
Each object produces one value.

**Comment by longmalongma** [comment]
> Each object produces one value.

Is there a difference in the order of the 3 masks?There are 6 orders of 3 masks.

**Comment by hkchengrex** [comment]
One mask is encoded as the primary mask at a time. The other argument, as I said, "is the sum of all other masks". The order is irrelevant.
