### ISSUE TITLE
Do you use davis 2016 in main training?

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#98]
You said that you perform main training on DAVIS 2016 and 2017, but it seems that you only use DAVIS 2017 in the code. May I ask where do you use DAVIS 2016 in training?

**Comment by hkchengrex** [comment]
Wait, where did I say I use DAVIS 2016 for main training? 
DAVIS 2016 is just a subset of 2017.

**Comment by zhouweii234** [comment]
![5e587949e8b873a6d282462500605d4](https://user-images.githubusercontent.com/62086490/140602682-e6f82c1b-19c9-4d9f-b1c2-0e2f80fb2a38.png)
Here
